import Foundation

func T(_ key: String) -> String {
    let lang = UserDefaults.standard.string(forKey: "appLanguage") ?? "en"
    if lang == "he" {
        return hebrewStrings[key] ?? key
    }
    return key
}

private let hebrewStrings: [String: String] = [
    "Appearance": "מראה",
    "Liquid Glass": "זכוכית נוזלית (Liquid Glass)",
    "Show in Dock": "הצג ב-Dock",
    "Theme Color": "צבע נושא",
    "Recording": "הקלטה",
    "Show Countdown": "הצג ספירה לאחור",
    "3-second countdown before recording starts": "ספירה לאחור של 3 שניות לפני תחילת ההקלטה",
    "Auto-open Recording": "פתח הקלטה אוטומטית",
    "Automatically open the video after saving": "פתח את הווידאו אוטומטית לאחר השמירה",
    "Launch at Login": "הפעל בעת התחברות",
    "Start in menu bar when you log in": "התחל בשורת התפריטים בעת התחברות",
    "Save Location": "מיקום שמירה",
    "Default Video Player": "נגן וידאו כברירת מחדל",
    "System Default": "ברירת מחדל של המערכת",
    "QuickTime Player": "QuickTime Player",
    "Choose Application...": "בחר יישום...",
    "Shortcut & App": "קיצורי דרך ואפליקציה",
    "Global Hotkey": "קיצור דרך גלובלי",
    "Choose the shortcut to start/stop recording": "בחר את קיצור הדרך להתחלה/עצירה של הקלטה",
    "Quit Warning": "אזהרת יציאה",
    "Show confirmation prompt when quitting the app (⌘Q)": "הצג בקשת אישור בעת יציאה מהאפליקציה (⌘Q)",
    "Change": "שנה",
    "Language / שפה": "Language / שפה",
    "Language": "שפה",
    "English": "English",
    "עברית": "עברית",
    "Record": "הקלט",
    "Cancel": "ביטול",
    "Options": "אפשרויות",
    "Countdown Timer": "טיימר ספירה לאחור",
    "None": "ללא",
    "3 seconds": "3 שניות",
    "5 seconds": "5 שניות",
    "Open when done": "פתח בסיום",
    "Close (Esc)": "סגור (Esc)",
    "Record Screen": "הקלט מסך",
    "Record Window": "הקלט חלון",
    "Record Selection": "הקלט אזור נבחר",
    "Record both screens side by side": "הקלט שני מסכים זה לצד זה",
    "System Audio": "שמע מערכת",
    "Microphone": "מיקרופון",
    "Screen Recorder": "מקליט מסך",
    "%@ to start / stop": "%@ להתחלה / עצירה",
    "Recordings": "הקלטות",
    "Total Size": "גודל כולל",
    "Total Duration": "משך זמן כולל",
    "Search recordings...": "חפש הקלטות...",
    "No recordings yet": "אין הקלטות עדיין",
    "No results found": "לא נמצאו תוצאות",
    "Press %@ or the button to start recording": "לחץ %@ או על הכפתור כדי להתחיל בהקלטה",
    "Try a different search term": "נסה מונח חיפוש שונה",
    "Saving recording...": "שומר הקלטה...",
    "Stop Recording": "עצור הקלטה",
    "Start Recording": "התחל הקלטה",
    "%@ shortcut": "קיצור %@",
    "Open": "פתח",
    "Reveal in Finder": "הצג ב-Finder",
    "Delete": "מחק",
    "✓  None": "✓  ללא",
    "✓  3 seconds": "✓  3 שניות",
    "✓  5 seconds": "✓  5 שניות",
    "Recording starts in %lld...": "ההקלטה תתחיל בעוד %lld...",
    "Recording Options": "אפשרויות הקלטה",
    "Settings": "הגדרות",
    "Open App": "פתח אפליקציה",
    "✓  Open when done": "✓  פתח בסיום",
    "Missing Screen Recording permission. If already checked, toggle it off and back on in System Settings > Privacy & Security > Screen Recording.": "חסרה הרשאת הקלטת מסך. אם כבר סימנת אותה, נסה לבטל ולהפעיל מחדש ב-הגדרות המערכת > פרטיות ואבטחה > הקלטת מסך.",
    "No display found.": "לא נמצא מסך.",
    "Recording failed: ": "ההקלטה נכשלה: ",
    "%dh %dm": "%d ש' %d ד'",
    "%dm": "%d ד'",
    "%.0f MB": "%.0f MB",
    "%.1f GB": "%.1f GB",
    "%.0f KB": "%.0f KB",
    "%.1f MB": "%.1f MB",
    "Media Control (F8 - Keyboard)": "בקרת מדיה (F8 - מקלדת)",
    "Send Play on record": "שלח נגן (Play) בהקלטה",
    "Send Pause on finish": "שלח השהה (Pause) בסיום",
    "✓  Send Play on record": "✓  שלח נגן (Play) בהקלטה",
    "✓  Send Pause on finish": "✓  שלח השהה (Pause) בסיום"
]
